# Site settings
title: Memoria IO, S.L
email: contact@memoria.io
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://memoria.io" # the base hostname & protocol for your site

linkedin_username: https://www.linkedin.com/company/m-io/
github_username: memoria-io

# Build settings
markdown: kramdown
