url: https://memoria-io.github.io
baseurl: /

# Site settings
title: Ismail Marmoush
email: ismail@marmoush.com
description: "memoria.io is the virtual organization behind Memoria, and memoria is a set of Web/Mobile/IoT Apps which will hopefully help us survive distractions, and stay focused on things that matter."


# Team names, titles and social links
people:
- name: Ismail Marmoush
  pic: 1
  position: Lead Engineer
  social:
    - title: twitter
      url: https://twitter.com/ismailmarmoush
    - title: facebook
      url: #
    - title: stack-overflow
      url: https://stackoverflow.com/users/263215/ismail-marmoush
    - title: github
      url: https://github.com/ismailmarmoush

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/ismailmarmoush

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
