# Site settings
title: Memoria IO, S.L
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://memoria.io" # the base hostname & protocol for your site

linkedin_username: m-io
twitter_username: memoria_io
github_username: memoria-io

# Build settings
markdown: kramdown
